local blue_shade = {
  alice_blue = "#",
  aqua = "#",
  argentinian_blue = "#",
  azure = "#",
  baby_blue = "#",
  berkeley_blue = "#",
  bice = "#",
  bleu_de_france = "#",
  blue_munsell = "#",
  blue_ncs = "#",

  blue_pantone = "#",
  blue_gray = "#",
  blue_green = "#",
  blue_violet = "#",
  blondi_blue = "#",
  brandeis_blue = "#",
  byzantine_blue = "#",
  cambridge_blue = "#",
  capri = "#",
  carolina_blue = "#",

  celestial_blue = "#",
  celtic_blue = "#",
  cerulean = "#",
  cobalt_blue = "#",
  columbia_blue = "#",
  cornflower_blue = "#",
  cyan = "#",
  dark_blue = "#",
  deep_sky_blue = "#",
  delft_blue = "#",

  dodger_blue = "#",
  duke_blue = "#",
  egyptian_blue = "#",
  electric_blue = "#",
  electric_indigo = "#",
  eton_blue = "#",
  french_blue = "#",
  glaucous = "#",
  haint_blue = "#",
  honolulu_blue = "#",

  horizon_blue = "#",
  indigo = "#",
  indigo_dye = "#",
  international_klein_blue = "#",
  iris = "#",
  jordy_blue = "#",
  lapis_lazuli = "#",
  lavender = "#",
  lavender_gray = "#",
  lavendar_mist = "#",

  light_blue = "#",
  light_sky_blue = "#",
  majorelle_blue = "#",
  marian_blue = "#",
  maya_blue = "#",
  medium_blue = "#",
  midnight_blue = "#",
  moroccan_blue = "#",
  navy_blue = "#",
  neon_blue = "#",

  non_photo_blue = "#",
  oxford_blue = "#",
  palatinate_blue = "#",
  pale_azure = "#",
  penn_blue = "#",
  periwinkle = "#",
  persian_blue = "#",
  persian_indigo = "#",
  phthalo_blue = "#",
  picton_blue = "#",

  pigment_blue = "#",
  polynesian_blue = "#",
  powder_blue = "#",
  process_blue = "#",
  prussian_blue = "#",
  raf_blue = "#",
  resolution_blue = "#",
  risd_blue = "#",
  royal_blue = "#",
  ruddy_blue = "#",

  sapphire = "#",
  savoy_blue = "#",
  silver_lake_blue = "#",
  sky_blue = "#",
  smalt = "#",
  space_cadet = "#",
  steel_blue = "#",
  tang_blue = "#",
  teal = "#",
  turquoise = "#",

  usaf_blue = "#",
  ultramarine = "#",
  united_nations_blue = "#",
  u_of_t_blue = "#",
  uranian_blue = "#",
  vista_blue = "#",
  yale_blue = "#",
  yinmn_blue = "#",
  zaffer = "#",


}
return blue_shade;
