local brown_shade = {
  auburn = "#",
  almond = "#",
  beaver = "#",
  beige = "#",
  bister = "#",
  black_bean = "#",
  black_olive = "#",
  bole = "#",
  bone = "#",
  bronze = "#",

  brown = "#",
  brown_sugar = "#",
  buff = "#",
  burgundy = "#",
  burnt_sienna = "#",
  burnt_amber = "#",
  camel = "#",
  caput_mortuum = "#",
  caramel = "#",
  chamoisee = "#",

  chestnut = "#",
  chocolate = "#",
  citron = "#",
  cocoa_brown = "#",
  coffee = "#",
  copper = "#",
  cordovan = "#",
  coyote = "#",
  desert_sand = "#",
  drab_dark_brown = "#",

  dun = "#",
  earth_yellow = "#",
  ecru = "#",
  fallow = "#",
  falun_red = "#",
  fawn = "#",
  field_drab = "#",
  fulvous = "#",
  golden_brown = "#",
  goldenrod = "#",

  harvest_gold = "#",
  khaki = "#",
  kobe = "#",
  kobicha = "#",
  lion = "#",
  liver = "#",
  mahogany = "#",
  maroon = "#",
  milk_chocolate = "#",
  ocher = "#",

  raw_umber = "#",
  red_brown = "#",
  redwood = "#",
  rufous = "#",
  russet = "#",
  rust = "#",
  sand = "#",
  sandy_brown = "#",
  satin_sheen_gold = "#",
  seal_brown = "#",

  sepia = "#",
  sienna = "#",
  sinopia = "#",
  tan = "#",
  taupe = "#483C32",
  tawny = "#",
  titian_red = "#",
  tuscan_red = "#",
  umber = "#",
  van_dyke = "#",

  walnut_brown = "#",
  wenge = "#",
  wheat = "#",
  wine_red = "#",

}
return brown_shade
