local green_shade = {
  apple_green = "#",
  aquamarine = "#",
  asparagus = "#",
  avacado = "#",
  biege = "#",
  blue_green = "#",
  bottle_green = "#",
  bright_green = "#",
  british_racing_green = "#",
  brunswick_green = "#",

  cadmium_green = "#",
  cambridge_blue = "#",
  celadon = "#",
  chartreuse = "#",
  chartreuse_web = "#",
  dark_green = "#",
  dark_spring_green = "#",
  emerald = "#",
  erin = "#",
  fern_green = "#",

  forest_green = "#",
  green_earth = "#",
  harlequin = "#",
  honeydew = "#",
  hookers_green = "#",
  hungarian_green = "#",
  hunter_green = "#",
  india_green = "#",
  islamic_green = "#",
  jade = "#",

  jungle_green = "#",
  khaki = "#",
  kelly_green = "#",
  lawn_green = "#",
  light_blue = "#",
  light_green = "#",
  lime = "#",
  lime_web = "#",
  lincoln_green = "#",
  magic_mint = "#",

  malachite = "#",
  mantis = "#",
  marrs_green = "#",
  medium_sea_green = "#",
  midnight_green = "#",
  mint = "#",
  mint_cream = "#",
  msu_green = "#",
  myrtle = "#",
  neon_green = "#",


  office_green = "#",
  olive = "#",
  olive_drab = "#",
  olivine = "#",
  olo = "#",
  pakistan_green = "#",
  paris_green = "#",
  pear = "#",
  persian_green = "#",
  pigment_green = "#",

  pine_green = "#",
  pistachio = "#",
  phthalo_green = "#",
  reseda_green = "#",
  rifle_green = "#",
  robin_egg_blue = "#",
  sage = "#",
  sap_green = "#",
  sea_green = "#",
  sgbus_green = "#",

  shamrock_green = "#",
  spring_bud = "#",
  spring_green = "#",
  tea_green = "#",
  teal = "#",
  turquoise = "#",
  verdigris = "#",
  viridian = "#"
}

return green_shade;
