local orange_shade = {
  aerospace_orange = "#",
  alloy_orange = "#",
  amber = "#",
  apricot = "#",
  atomic_tangerine = "#",
  brown = "#",
  burnt_orange = "#",
  butterscotch = "#",
  carrot_orange = "#",
  champagne = "#",

  orange_chrome = "#",
  coral = "#FF7F50",
  dark_orange_web = "#",
  desert_sand_color = "#",
  engineering_orange = "#",
  flame = "#",
  gold = "#",
  golden_gate_bridge = "#",
  goldenrod = "#",
  light_orange = "#",

  mahogany = "#",
  marigold = "#",
  melon = "#",
  orange_crayola = "#",
  orange_pantone = "#",
  orange_peel = "#",
  orange_web = "#",
  orange_wheel = "#",
  papaya_whip = "#",
  peach = "#",

  persian_orange = "#",
  persimmon = "#",
  portland_orange = "#",
  princeton_orange = "#",
  pumpkin = "#",
  red_lead = "#",
  rust = "#",
  safery_orange = "#",
  saffron = "#",
  spanish_orange = "#",

  tangelo = "#",
  tangerine = "#",
  tawny = "#",
  tigers_eye = "#",
  titian_red = "#",
  ut_orange = "#",
  vermillion = "#",
  xanthous = "#",
}
return orange_shade
