local pink_shade = {
  amaranth = "#",
  amaranth_pink = "#",
  baker_miller_pink = "#",
  barbie_pink = "#",
  blush = "#",
  brilliant_rose = "#",
  brink_pink = "#",
  carnation_pink = "#",
  cameo_pink = "#",
  cerise = "#",

  champagne_pink = "#",
  cherry_blossom_pink = "#",
  china_rose = "#",
  coral = "#",
  colral_pink = "#",
  cordovan = "#",
  cyclamen = "#",
  deep_pink = "#",
  dogwood_rose = "#",
  english_lavender = "#",

  fairy_tale = "#",
  french_rose = "#",
  fuchsia = "#",
  fuchsia_rose = "#",
  folly = "#",
  heliotrope = "#",
  hollywood_cerise = "#",
  hot_magenta = "#",
  hot_pink = "#",
  lavender_blush = "#",

  lavender_glitter = "#",
  lavender_pink = "#",
  lilac = "#",
  lilac_luster = "#",
  liseran_purple = "#",
  lusty_gallant = "#",
  magenta = "#",
  mauvelous = "#",
  medium_deep_rose = "#",
  mexican_pink = "#",

  melon = "#",
  mimi_pink = "#",
  misty_rose = "#",
  mountbatten_pink = "#",
  mystic_pearl = "#",
  old_rose = "#",
  orchid_pink = "#",
  pale_dogwood = "#",
  pale_purple = "#",
  peach = "#",

  persian_rose = "#",
  persian_pink = "#",
  phlox = "#",
  piggy_pink = "#",
  pink = "#",
  pink_flamingo = "#",
  pink_lavender = "#",
  pink_lace = "#",
  pink_sherbert = "#",
  puce = "#",

  raspberry = "#",
  razzle_dazzle_rose = "#",
  razzmatazz = "#",
  red_violet = "#",
  raspberry_rose = "#",
  rose = "#",
  rose_bonbon = "#",
  rose_ebony = "#",
  rose_pink = "#",
  rose_pompadour = "#",

  rose_quartz = "#",
  rose_red = "#",
  rose_taupe = "#",
  rose_vale = "#",
  rosewoord = "#",
  rosy_brown = "#",
  salmon_crayola = "#",
  salmon_pink = "#",
  seashell = "#",
  shocking_pink = "#",

  tea_rose = "#",
  tickle_me_pink = "#",
  telemagenta = "#",
  thulian_pink = "#",
  ultra_pink = "#",
  very_light_rose = "#",
  wild_strawberry = "#",

}
return pink_shade
