local violet_shade = {

  african_violet = "#",
  amethyst = "#",
  blue_bell = "#",
  blue_violet = "#",
  blurple = "#",
  burgundy = "#",
  byzantium = "#",
  caput_mortuum = "#",
  calestial_blue = "#",
  cerise = "#",


  chinese_violet = "#",
  cotton_candy = "#",
  dark_purple = "#",
  dark_violet = "#",
  eggplant = "#",
  electric_indigo = "#",
  electric_purple = "#",
  electric_violet = "#",
  eminence = "#",
  english_lavender = "#",

  english_violet = "#",
  fairy_tail = "#",
  fandango = "#",
  fandango_pink = "#",
  franch_mauve = "#",
  french_violet = "#",
  fuchsia = "#",
  grape = "#",
  heliotrope = "#",
  indigo = "#",

  iris = "#",
  japanese_violet = "#",
  jazzberry_jam = "#",
  languid_lavender = "#",
  lavender_blush = "#",
  lavender_crayola_I = "#",
  lavender_gray = "#",
  lavender_pink = "#",
  lavender_floral = "#",
  lavender_web = "#",

  lilac = "#",
  magenta = "#",
  majorelle_blue = "#",
  mardi_gras = "#",
  mauve = "#",
  mauveine = "#",
  maximum_blue_purple = "#",
  maximum_red_purple = "#",
  medium_purple = "#",
  medium_slate_blue = "#",

  middle_blue_purple = "#",
  mimi_pink = "#",
  mountbatten_pink = "#",
  mulberry = "#",
  murrey = "#",
  old_lavender = "#",
  orchid = "#",
  palatinate = "#",
  pale_lavender = "#",
  pale_purple = "#",

  periwinkle = "#",
  periwinkle_crayola = "#",
  persian_indigo = "#",
  persian_pink = "#",
  petunia = "#",
  pink_lace = "#",
  pink_lavender = "#",
  plum_web = "#",
  pomp_and_power = "#",
  psychedelic_purple = "#",

  puce = "#",
  purple = "#",
  purple_heart = "#",
  purple_mountain_majesty = "#",
  purpureus = "#",
  rebecca_purple = "#",
  red_violet = "#",
  rose_pink = "#",
  royal_purple = "#",
  russian_violet = "#",

  slate_blue = "#",
  soap = "#",
  steel_pink = "#",
  tekhelet = "#",
  thistle = "#",
  tropical_indigo = "#",
  twilight_lavender = "#",
  tyrian_purple = "#",
  ultra_pink = "#",
  ultra_violet = "#",

  veronica = "#",
  vibrant_purple = "#",
  violet = "#",
  violet_red = "#",
  violet_web_color = "#",
  vivid_violet = "#",
  wisteria = "#",
}

local purple_shade = {
  african_violet = "#",
  amaranth_purple = "#AB274F",
  amethyst = "#",
  blue_violet = "#",
  blurple = "#",
  burgundy = "#",
  byzantine = "#",
  byzantium = "#",
  cerise = "#",
  chinese_violet = "#",


  cobalt_violet = "#",
  dark_purple = "#",
  dark_violet = "#",
  eggplant = "#",
  electric_purple = "#",
  electric_violet = "#",
  eminence = "#",
  english_lavender = "#",
  french_mauve = "#",
  french_violet = "#",

  fuchsia = "#",
  grape = "#",
  heliotrope = "#",
  indigo = "#",
  indigo_web_color = "#",
  jazzberry_jam = "#",
  japanese_violet = "#",
  ksu_purple = "#",
  languid_lavender = "#",
  lavender_blush = "#",

  lavender_crayola_I = "#",
  lavender_gray = "#",
  lavender_mist = "#",
  lavender_pink = "#",
  lavender_floral = "#",
  lilac = "#",
  liseran_purple = "#",
  magenta = "#",
  mardi_gras = "#",
  mauve = "#",

  mauveine = "#",
  maximum_blue_purple = "#",
  maximum_red_purple = "#",
  medium_purple = "#",
  mexican_purple = "#",
  middle_blue_purple = "#",
  middle_purple = "#",
  mulberry = "#",
  murrey = "#",

  northwestern_purple = "#",
  old_lavender = "#",
  orchid = "#",
  palatinate = "#",
  pale_purple = "#",
  pansy_purple = "#",
  patriarch = "#",
  pearly_purple = "#",
  periwinkle = "#",
  pink_lavender = "#",

  plum = "#",
  plum_web = "#",
  pomp_and_power = "#",
  psychedelic_purple = "#",
  purple_encycolorpedia = "#",
  purple_heart = "#",
  purple_munsell = "#",
  purple_mountains_majesty = "#",
  purple = "#",
  purpureus = "#",

  purple_pizzazz = "#",
  razzle_dazzle_purple = "#",
  rebecca_purple = "#",
  red_purple = "#",
  red_violet = "#",
  royal_purple = "#",
  rose_pink = "#",
  thistle = "#",
  traffic_purple = "#",
  twilight_lavender = "#",

  tyrian_purple = "#",
  veronica = "#",
  vibrant_purple = "#",
  violet = "#",
  vivid_violet = "#",
  wisteria = "#",
}

local violet_and_purple_shade = {
  violet_shade,
  purple_shade
}

return violet_and_purple_shade
