local red_shade = {
  alizaran_crimson = "#E32636",
  amaranth = "#AB274F",
  barn_red = "#7C0902",
  bittersweet_shimmer = "#BF4F51",
  blood_red = "#660000",
  brink_pink = "#FB607F",
  burgundy = "#800020",
  candy_apple_red = "#FF0800",
  cantaloupe_melon = "#FDBCB4",
  cardinal = "#C51E3A",

  carmine = "#960018",
  carnelian = "#B31B1B",
  cerise = "#DE3163",
  chili_red = "#E23D28",
  chocolate_cosmos = "#58111A",
  cinnabar = "#E44D2E",
  claret = "#7F1734",
  coquelicot = "#FF3800",
  coral = "#F88379",
  cordovan = "#893F45",

  crimson = "#",
  dark_red = "#",
  falun_red = "#",
  fire_brick = "#",
  folly = "#",
  garnet = "#",
  imperial_red = "#",
  iron_oxide_red = "#",
  jasper = "#",


  light_coral = "#",
  light_red = "#",
  madder = "#",
  mahogany = "#",
  maroon = "#",
  misty_rose = "#",
  off_red = "#",
  old_rose = "#",
  oxblood = "#",
  persian_red = "#",

  pigment_red = "#",
  pink = "#",
  poppy = "#",
  puce = "#",
  raspberry = "#",
  red = "#FF0000",
  red_brown = "#",
  red_crayola = "#",
  red_munsell = "#",
  red_ncs = "#",

  red_pantone = "#",
  redwood = "#",
  rose = "#",
  rose_ebony = "#",
  rose_red = "#",
  rose_taupe = "#FF0000",
  rose_vale = "#",
  rosewood = "#",
  rosso_corsa = "#",
  rosy_brown = "#",

  ruby = "#",
  rust = "#",
  rusty_red = "#",
  salmon = "#",
  salmon_pink = "#",
  scarlet = "#FF0000",
  spanish_red = "#",
  tea_rose = "#",
  tomato = "#",
  turkey_red = "#",

  tuscan_red = "#",
  venetian_red = "#",
  vermilion = "#",
  wine = "#",
}
return red_shade
