local white_shade = {
  alabaster = "#",
  alice_blue = "#",
  almond = "#",
  anti_flash_white = "#",
  antique_white = "#",
  azure_white = "#",
  baby_powder = "#",
  beige = "#",
  bone = "#",
  champagne = "#",

  cornsilk = "#",
  cool_mint = "#",
  cosmic_latte = "#",
  cream = "#",
  cultured_pearl = "#",
  dutch_white = "#",
  eggshell = "#",
  extra_light_almond = "#",
  flax = "#",
  floral_white = "#",

  ghost_white = "#",
  honeydew = "#",
  isabelline = "#",
  ivory = "#",
  lavender_blush = "#",
  lemon_chiffon = "#",
  linen = "#",
  magnolia = "#",
  mint_cream = "#",
  misty_rost = "#",

  navajo_white = "#",
  nyanza = "#",
  old_lace = "#",
  papaya_white = "#",
  parchment = "#",
  peach = "#",
  pearl = "#",
  platinum = "#",
  seasalt = "#",
  seashell = "#",

  snow = "#",
  snow_drift = "#",
  vanilla = "#",
  very_light_rose = "#",
  white = "#",
  white_smoke = "#",
}
return white_shade
